requires 'Acme::Cow';
requires 'Crypt::Ed25519';
requires 'Data::Processor';
requires 'Email::Address', '>= 1.910';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Email::Valid';
requires 'GeoIP2';
requires 'IO::Socket::SSL';
requires 'LaTeX::Encode';
requires 'Mojo::IRC';
requires 'Mojo::SQLite';
requires 'Mojolicious';
requires 'Mozilla::CA';
requires 'Net::Domain::TLD';
requires 'Regexp::IPv4';
requires 'Regexp::IPv6';
requires 'Sort::Versions';
